In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import warnings
warnings.filterwarnings("ignore")
import tensorflow as tf
from tensorflow.keras import Sequential # it is used to build ANN
from tensorflow.keras.layers import Dense # it is used to add hidden layers
from sklearn.metrics import classification_report #evaulation

In [4]:
df=pd.read_csv("diabetes.csv")
df.head()


Pregnancies  Glucose  BloodPressure  SkinThickness  Insulin   BMI  \
0            6      148             72             35        0  33.6   
1            1       85             66             29        0  26.6   
2            8      183             64              0        0  23.3   
3            1       89             66             23       94  28.1   
4            0      137             40             35      168  43.1   

   DiabetesPedigreeFunction  Age  Outcome  
0                     0.627   50        1  
1                     0.351   31        0  
2                     0.672   32        1  
3                     0.167   21        0  
4                     2.288   33        1

In [5]:
x=df.iloc[:,:-1].values
x

array([[  6.   , 148.   ,  72.   , ...,  33.6  ,   0.627,  50.   ],
       [  1.   ,  85.   ,  66.   , ...,  26.6  ,   0.351,  31.   ],
       [  8.   , 183.   ,  64.   , ...,  23.3  ,   0.672,  32.   ],
       ...,
       [  5.   , 121.   ,  72.   , ...,  26.2  ,   0.245,  30.   ],
       [  1.   , 126.   ,  60.   , ...,  30.1  ,   0.349,  47.   ],
       [  1.   ,  93.   ,  70.   , ...,  30.4  ,   0.315,  23.   ]])

In [6]:
y=df['Outcome'].values
y

array([1, 0, 1, 0, 1, 0, 1, 0, 1, 1, 0, 1, 0, 1, 1, 1, 1, 1, 0, 1, 0, 0,
       1, 1, 1, 1, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 1, 1, 0, 0, 0, 1,
       0, 1, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 1, 0,
       1, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0,
       1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1,
       1, 1, 0, 0, 1, 1, 1, 0, 0, 0, 1, 0, 0, 0, 1, 1, 0, 0, 1, 1, 1, 1,
       1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0,
       1, 1, 0, 0, 0, 1, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 1, 1, 0, 0, 0, 1,
       0, 1, 0, 1, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 0, 0, 1, 1, 0, 1, 0, 1,
       1, 1, 0, 0, 0, 0, 0, 0, 1, 1, 0, 1, 0, 0, 0, 1, 1, 1, 1, 0, 1, 1,
       1, 1, 0, 0, 0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 0, 1, 1, 1, 1, 0, 0, 0,
       1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 1, 0, 1, 0, 0,
       1, 0, 1, 0, 0, 1, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 1, 1, 0,
       0, 1, 0, 0, 0, 1, 1, 1, 0, 0, 1, 0, 1, 0, 1,

In [7]:
#split data into training and testing
from sklearn.model_selection import train_test_split
xtrain,xtest,ytrain,ytest=train_test_split(x,y,test_size=0.30,random_state=1)
xtrain

array([[1.50e+01, 1.36e+02, 7.00e+01, ..., 3.71e+01, 1.53e-01, 4.30e+01],
       [0.00e+00, 9.70e+01, 6.40e+01, ..., 3.68e+01, 6.00e-01, 2.50e+01],
       [1.00e+00, 1.16e+02, 7.00e+01, ..., 2.74e+01, 2.04e-01, 2.10e+01],
       ...,
       [1.30e+01, 1.26e+02, 9.00e+01, ..., 4.34e+01, 5.83e-01, 4.20e+01],
       [4.00e+00, 1.71e+02, 7.20e+01, ..., 4.36e+01, 4.79e-01, 2.60e+01],
       [9.00e+00, 1.02e+02, 7.60e+01, ..., 3.29e+01, 6.65e-01, 4.60e+01]])

In [8]:
from sklearn.preprocessing import StandardScaler
sc=StandardScaler()
xtrain=sc.fit_transform(xtrain)
xtest=sc.transform(xtest)

In [9]:
#Step1 :- init the model
ann = Sequential()

#Step 2 :- add layers to model
ann.add(Dense(units = 6,activation= "relu" )) #Create 0ne layer
ann.add(Dense(units = 1, activation = "sigmoid"))

#step 3 :- establish connection between layers
ann.compile(optimizer="adam", loss="binary_crossentropy",metrics=['accuracy'])

#step 4 :- train the model
ann.fit(xtrain,ytrain,batch_size=30,epochs=100)

#step 5:- make prediction
ypred = ann.predict(xtest)

Epoch 1/100
18/18 [==============================] - 1s 2ms/step - loss: 0.8685 - accuracy: 0.4004
Epoch 2/100
18/18 [==============================] - 0s 2ms/step - loss: 0.8235 - accuracy: 0.4339
Epoch 3/100
18/18 [==============================] - 0s 2ms/step - loss: 0.7830 - accuracy: 0.4693
Epoch 4/100
18/18 [==============================] - 0s 2ms/step - loss: 0.7488 - accuracy: 0.4916
Epoch 5/100
18/18 [==============================] - 0s 2ms/step - loss: 0.7189 - accuracy: 0.5177
Epoch 6/100
18/18 [==============================] - 0s 2ms/step - loss: 0.6935 - accuracy: 0.5419
Epoch 7/100
18/18 [==============================] - 0s 2ms/step - loss: 0.6711 - accuracy: 0.5773
Epoch 8/100
18/18 [==============================] - 0s 2ms/step - loss: 0.6518 - accuracy: 0.6034
Epoch 9/100
18/18 [==============================] - 0s 2ms/step - loss: 0.6359 - accuracy: 0.6276
Epoch 10/100
18/18 [==============================] - 0s 2ms/step - loss: 0.6208 - accuracy: 0.6536
Epoch 11/

In [10]:

# step 6 -: set the threshold.
ypred=np.where(ypred<0.5,0,1)

ypred

array([[1],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [1],
       [1],
       [0],
       [1],
       [0],
       [0],
       [0],
       [0],
       [1],
       [0],
       [1],
       [0],
       [0],
       [1],
       [0],
       [1],
       [0],
       [0],
       [1],
       [0],
       [0],
       [1],
       [0],
       [1],
       [0],
       [0],
       [0],
       [1],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [1],
       [1],
       [0],
       [0],
       [0],
       [0],
       [1],
       [0],
       [1],
       [0],
       [1],
       [0],
       [1],
       [0],
       [1],
       [0],
       [1],
       [0],
       [0],
       [0],
       [0],
       [0],
       [1],
       [1],
       [1],
       [1],
       [1],
       [0],
       [1],
       [0],
       [1],
       [0],
       [0],
       [1],
       [1],
       [0],
       [1],
    

In [11]:
print(classification_report(ytest,ypred))

              precision    recall  f1-score   support

           0       0.80      0.86      0.83       146
           1       0.73      0.62      0.67        85

    accuracy                           0.77       231
   macro avg       0.76      0.74      0.75       231
weighted avg       0.77      0.77      0.77       231



In [12]:
df.Outcome.value_counts()

0    500
1    268
Name: Outcome, dtype: int64

In [13]:
#Upsampling the data
df_majority = df[df.Outcome == 0]
df_minority = df[df.Outcome == 1]

In [14]:
df_majority.shape , df_minority.shape

((500, 9), (268, 9))

In [15]:
from sklearn.utils import resample

In [16]:
df_minority_upsampled = resample(df_minority, replace = "True",
                                 n_samples = 500,
                                 random_state=123)

In [17]:
df_upsampled = pd.concat([df_majority,df_minority_upsampled])
df_upsampled.Outcome.value_counts()

0    500
1    500
Name: Outcome, dtype: int64

In [18]:
x1=df_upsampled.iloc[:,:-1].values
x1

array([[1.00e+00, 8.50e+01, 6.60e+01, ..., 2.66e+01, 3.51e-01, 3.10e+01],
       [1.00e+00, 8.90e+01, 6.60e+01, ..., 2.81e+01, 1.67e-01, 2.10e+01],
       [5.00e+00, 1.16e+02, 7.40e+01, ..., 2.56e+01, 2.01e-01, 3.00e+01],
       ...,
       [2.00e+00, 1.05e+02, 8.00e+01, ..., 3.37e+01, 7.11e-01, 2.90e+01],
       [2.00e+00, 1.97e+02, 7.00e+01, ..., 3.47e+01, 5.75e-01, 6.20e+01],
       [3.00e+00, 1.71e+02, 7.20e+01, ..., 3.33e+01, 1.99e-01, 2.40e+01]])

In [19]:
y1=df_upsampled['Outcome'].values
y1

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,

In [20]:
#split data into training and testing
from sklearn.model_selection import train_test_split
xtrain,xtest,ytrain,ytest=train_test_split(x1,y1,test_size=0.30,random_state=1)
xtrain

array([[  3.   , 170.   ,  64.   , ...,  34.5  ,   0.356,  30.   ],
       [  9.   , 119.   ,  80.   , ...,  29.   ,   0.263,  29.   ],
       [  7.   , 114.   ,  66.   , ...,  32.8  ,   0.258,  42.   ],
       ...,
       [  0.   , 131.   ,   0.   , ...,  43.2  ,   0.27 ,  26.   ],
       [  1.   , 107.   ,  72.   , ...,  30.8  ,   0.821,  24.   ],
       [  2.   , 109.   ,  92.   , ...,  42.7  ,   0.845,  54.   ]])

In [21]:
from sklearn.preprocessing import StandardScaler
sc=StandardScaler()
xtrain=sc.fit_transform(xtrain)
xtest=sc.transform(xtest)

In [22]:
#Step1 :- init the model
ann = Sequential()

#Step 2 :- add layers to model
ann.add(Dense(units = 6,activation= "relu" )) #Create 0ne layer
ann.add(Dense(units = 1, activation = "sigmoid"))

#step 3 :- establish connection between layers
ann.compile(optimizer="adam", loss="binary_crossentropy",metrics=['accuracy'])

#step 4 :- train the model
ann.fit(xtrain,ytrain,batch_size=30,epochs=100)

#step 5:- make prediction
ypred = ann.predict(xtest)

Epoch 1/100
24/24 [==============================] - 0s 1ms/step - loss: 0.7875 - accuracy: 0.5643
Epoch 2/100
24/24 [==============================] - 0s 2ms/step - loss: 0.7504 - accuracy: 0.5843
Epoch 3/100
24/24 [==============================] - 0s 2ms/step - loss: 0.7189 - accuracy: 0.5957
Epoch 4/100
24/24 [==============================] - 0s 2ms/step - loss: 0.6897 - accuracy: 0.6129
Epoch 5/100
24/24 [==============================] - 0s 2ms/step - loss: 0.6648 - accuracy: 0.6271
Epoch 6/100
24/24 [==============================] - 0s 1ms/step - loss: 0.6436 - accuracy: 0.6457
Epoch 7/100
24/24 [==============================] - 0s 2ms/step - loss: 0.6251 - accuracy: 0.6714
Epoch 8/100
24/24 [==============================] - 0s 2ms/step - loss: 0.6086 - accuracy: 0.6886
Epoch 9/100
24/24 [==============================] - 0s 3ms/step - loss: 0.5948 - accuracy: 0.7029
Epoch 10/100
24/24 [==============================] - 0s 2ms/step - loss: 0.5824 - accuracy: 0.7200
Epoch 11/

In [23]:
# step 6 -: set the threshold.
ypred=np.where(ypred<0.5,0,1)

ypred

array([[1],
       [1],
       [0],
       [0],
       [0],
       [1],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [0],
       [0],
       [1],
       [1],
       [0],
       [1],
       [0],
       [1],
       [0],
       [0],
       [0],
       [0],
       [1],
       [1],
       [1],
       [0],
       [1],
       [0],
       [0],
       [1],
       [1],
       [1],
       [0],
       [0],
       [0],
       [1],
       [0],
       [0],
       [0],
       [0],
       [0],
       [1],
       [1],
       [0],
       [1],
       [1],
       [0],
       [0],
       [0],
       [1],
       [0],
       [1],
       [1],
       [1],
       [1],
       [0],
       [1],
       [0],
       [0],
       [0],
       [0],
       [0],
       [1],
       [0],
       [1],
       [0],
       [0],
       [0],
    

In [24]:
print(classification_report(ytest,ypred))

              precision    recall  f1-score   support

           0       0.76      0.75      0.76       149
           1       0.76      0.77      0.76       151

    accuracy                           0.76       300
   macro avg       0.76      0.76      0.76       300
weighted avg       0.76      0.76      0.76       300

